### ISSUE TITLE
Meething behind SSL offloading reverse proxy?

### ISSUE THREAD

**Issue by pwFoo** [meething/meething-docker#1]
I habe a reverse proxy for SSL offloading. Would IT possible to run meething without SSL certificate behind a proxy?

**Comment by lmangani** [comment]
Yes

**Comment by pwFoo** [comment]
Ok, so no need for a certificate inside of the container? I'll try to disable SSL in config file and deploy.

**Comment by pwFoo** [comment]
Looks good and starting up without certificate / revproxy. 
Error with port binding in new issue #2
